Repository shivamyadavrgipt/Social_media_management, pull requests merged in 2024-10, with the labels that each got.

#74 Resolves #58 - Added Landing Page
  public/illustration.png
  public/is14Logo.png
  public/is14Logosvg.svg
  src/App.jsx
  src/components/Navbar.jsx
  src/pages/LandingPage.css
  src/pages/LandingPage.jsx
Labels: level3, gssoc-ext, hacktoberfest-accepted

#102 Added a Dedicated "Contribution page"
  package.json
  src/App.jsx
  src/components/Navbar.jsx
  src/pages/Contributors.css
  src/pages/Contributors.jsx
Labels: level2, gssoc-ext

#135 I have added a User authentication of Signup page
  Backend/controllers/user.controller.js
  Backend/db/index.js
  Backend/models/user.model.js
  Backend/routes/user.route.js
  package-lock.json
  package.json
  src/App.jsx
  src/components/BasicNavbar.jsx
  src/index.css
  src/pages/LandingPage.css
  src/pages/LandingPage.jsx
  src/pages/SignUp.jsx
  src/pages/signup.css
Labels: level3, gssoc-ext, hacktoberfest-accepted

#142 Changed Chatbot Position for Better UI
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#122 Create greetings.yml
  .github/workflows/greetings.yml
Labels: level3, gssoc-ext

#153 I have added newsletter page in tool tab
  package-lock.json
  package.json
  src/App.jsx
  src/components/Navbar.jsx
  src/pages/Newsletter.css
  src/pages/Newsletter.jsx
Labels: level3, gssoc-ext

#160 Added logo
  index.html
  public/logo1.png
  public/logo2.png
Labels: level2, gssoc-ext, hacktoberfest-accepted

#161 Created CODE_OF_CONDUCT
  CODE_OF_CONDUCT
Labels: level1, gssoc-ext

#163 Fixed: "Greetings" workflow, designed to automatically send a warm, welcome to users who open new issues or pull requests in this repository.
  .github/workflows/greetings.yml
Labels: level1, gssoc-ext, hacktoberfest-accepted

#166 Update :- signUp and Login Form
  src/pages/LandingPage.jsx
  src/pages/SignUp.jsx
  src/pages/signup.css
  tailwind.config.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#167 Adding animeted Pre Loader
  src/App.jsx
  src/pages/PreLoader.jsx
  src/pages/Preloader.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#172 I have added dynamic contributors page to fetch data
  src/index.css
  src/pages/Contributors.css
  src/pages/Contributors.jsx
Labels: level3, gssoc-ext, hacktoberfest-accepted

#169 Update Dashboard.jsx
  src/pages/Dashboard.jsx
Labels: level1, gssoc-ext, hacktoberfest-accepted
