Repository shivamyadavrgipt/Social_media_management, pull requests merged in 2024-11, with the labels that each got.

#188 Fix navbar animations: resolved hover effects, rotation, and sizing issues
  src/components/Navbar.jsx
Labels: level2, gssoc-ext

#198 added:: Meta Tags, robots.txt, sitemaps for SEO Enhancement
  generate-sitemap.js
  package-lock.json
  package.json
  public/robots.txt
  public/sitemap.xml
  src/App.jsx
Labels: level2, gssoc-ext, hacktoberfest-accepted

#200 Update README.md
  README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#206 Added Settings Page
  src/pages/settings.css
  src/pages/settings.jsx
Labels: level3, gssoc-ext, hacktoberfest-accepted

#202 Add Scroll to top button
  package-lock.json
  package.json
  src/App.jsx
  src/components/TopButton.jsx
  src/pages/LandingPage.jsx
Labels: level1, level2, gssoc-ext, hacktoberfest-accepted

#212 Enhance the footer
  package-lock.json
  package.json
  src/components/Footer.jsx
Labels: level2, gssoc-ext, hacktoberfest-accepted

#214 Create SECURITY.md
  SECURITY.md
Labels: level2, gssoc-ext, hacktoberfest-accepted

#217 Update Footer.jsx
  src/components/Footer.jsx
Labels: level2, gssoc-ext, hacktoberfest-accepted
